#Exemplo de docker-componse para subir ambiente Wordpress com banco mariaDB

version: '3'

networks:
  wordpress_net:
    driver: bridge

volumes:
  mariadb_vol: {}
  wordpress_vol: {}

services:
  db:
    restart: always
    container_name: banco_de_dados
    image: mariadb
    networks:
      - wordpress_net
    volumes:
      - mariadb_vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: senha
      MYSQL_USER: senha
      MYSQL_PASSWORD: senha
  
  meublog:
    container_name: blog_wordpress
    restart: always
    #Indica que o serviço meublog vai esperar o serviço DB subir 
    #Para depois subir, pois depende do DB.
    depends_on:
      - db
    image: wordpress 
    networks:
      - wordpress_net
    volumes:
      - wordpress_vol:/var/www/html
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: senha
      WORDPRESS_DB_PASSWORD: senha
      WORDPRESS_DB_NAME: senha




